#ifndef COMMON_TYPES_H
#define COMMON_TYPES_H

#define SLICE_SIZE      100
#define SPACING_SIZE    25
#define MOUSE_SELECTION_OFFSET SPACING_SIZE/2 
#define GRID_POINT_SIZE 3
#define IN_OUT_RECT_WIDTH GRID_POINT_SIZE*5
#define WIRE_INTERACT_POINT_SIZE 8
#define LINE_THICKNESS 5

#endif  // COMMON_TYPES_H