#ifndef COMMON_TYPES_H
#define COMMON_TYPES_H

#define SLICE_SIZE      100
#define SPACING_SIZE    25
#define MOUSE_SELECTION_OFFSET SPACING_SIZE/2 
#define GRID_POINT_SIZE 3
#define WIRE_INTERACT_POINT_SIZE 8

#endif  // COMMON_TYPES_H